/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'skoner' at '19/01/16 9:17' with Gradle 2.6
 *
 * @author skoner, @date 19/01/16 9:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
