/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'skoner' at '9/02/16 9:57' with Gradle 2.6
 *
 * @author skoner, @date 9/02/16 9:57
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
